### ISSUE TITLE
Create list user API to list the all the user based on UserType(Admin/SuperAdmin),Status

### ISSUE THREAD

**Issue by dishanks9** [JJCSA/backend#15]

**Comment by dishanks9** [comment]
List Users API
This API will fetch a list of all the users based on the status (By default it will be pending). Admin will have functionality to select status and fetch list of users based on the Status. Based on the user type(Admin/Super Admin) data will be displayed on the Admin panel. 

Input will be :- RequesterId, UserType(Admin/SuperAdmin),Status
(? - Still need to think)
Output will be :-List User Object

**Comment by the-karanshah** [comment]
I have pushed the code to getuserapi branch which I was worked on. Since I was using my temp. POJOs earlier, I found it difficult to change the code with POJOs given in recent pull request given the complexity.
