### ISSUE TITLE
Finalize the fields required for User Onboarding

### ISSUE THREAD

**Issue by shah-tejas** [JJCSA/backend#77]
New User is considered active when they fill all the required details of their profile.
Till the user does not fill all the required fields of their profile, their access to the website will be limited and frontend should redirect user to fill their profile
Need to finalize these fields which decide if the user profile is completed

Acceptance Criteria:
- Implement the `UserService.hasUserCompletedOnboardingProfile()` method which checks if user has completed onboarding profile
- On User profile update check if `hasUserCompletedOnboardingProfile()`. If true, update user status to "Active"

**Comment by shah-tejas** [comment]
@Nishit-Gopani can you please add the final list of mandatory fields which need to be filled my user on approval.

**Comment by Nishit-Gopani** [comment]
First Name
Last Name 
Street / State / City / Zip Email Address 
DOB
LinkedIn URL 
Current Status 
Education Details ( University Name, Course , Start Date and Graduation Date)
Professional Experience (Company Name , Role , Location )


*** We can add or remove fields moving forward as per requirement***
